const settings = {
    number_of_robots: 20,
    robot_color: '#0f0',
    robot_starting_position_x: 15,
    robot_starting_position_y: 15,
    robot_width: 20,
    robot_movement_min: -1,
    robot_movement_max: 1,
    robot_population_size: 20,

    target_color: '#0f0',
    target_search_treshold: 10,
    target_width: 20,
};

const target_types = [
    {
        color: '#f00',
        shape: 'circle',
        width: settings.target_width,
        edible: true,
    },
    {
        color: '#ff0',
        shape: 'circle',
        width: settings.target_width,
        edible: true,
    },
    {
        color: '#00f',
        shape: 'circle',
        width: settings.target_width,
        edible: true,
    },
    {
        color: '#f00',
        shape: 'circle',
        width: settings.target_width + 10,
        edible: true,
    },
    {
        color: '#ff0',
        shape: 'circle',
        width: settings.target_width + 10,
        edible: true,
    },
    {
        color: '#00f',
        shape: 'circle',
        width: settings.target_width + 10,
        edible: true,
    },
    {
        color: '#f00',
        shape: 'rect',
        width: settings.target_width,
        edible: false,
    },
    {
        color: '#ff0',
        shape: 'rect',
        width: settings.target_width,
        edible: false,
    },
    {
        color: '#00f',
        shape: 'rect',
        width: settings.target_width,
        edible: false,
    },
    {
        color: '#f00',
        shape: 'rect',
        width: settings.target_width + 10,
        edible: false,
    },
    {
        color: '#ff0',
        shape: 'rect',
        width: settings.target_width + 10,
        edible: false,
    },
    {
        color: '#00f',
        shape: 'rect',
        width: settings.target_width + 10,
        edible: false,
    },
    {
        color: '#f00',
        shape: 'triangle',
        width: settings.target_width,
        edible: false,
    },
    {
        color: '#ff0',
        shape: 'triangle',
        width: settings.target_width,
        edible: false,
    },
    {
        color: '#00f',
        shape: 'triangle',
        width: settings.target_width,
        edible: false,
    },
    {
        color: '#f00',
        shape: 'triangle',
        width: settings.target_width + 10,
        edible: false,
    },
    {
        color: '#ff0',
        shape: 'triangle',
        width: settings.target_width + 10,
        edible: false,
    },
    {
        color: '#00f',
        shape: 'triangle',
        width: settings.target_width + 10,
        edible: false,
    },
];